namespace PMS.Domain.Entities.Reporting;

/// <summary>
/// Aggregated product sales data for reporting and analytics.
/// Stores cumulative sales metrics per product, updated periodically.
/// Only used by ReportingDbContext.
/// </summary>
public class ProductSalesAggregate
{
    public Guid Id { get; private set; }

    /// <summary>
    /// Reference to the product (not a FK - products may be deleted).
    /// </summary>
    public Guid ProductId { get; private set; }

    /// <summary>
    /// Product SKU snapshot.
    /// </summary>
    public string Sku { get; private set; } = null!;

    /// <summary>
    /// Product name snapshot.
    /// </summary>
    public string ProductName { get; private set; } = null!;

    /// <summary>
    /// Total quantity ever sold.
    /// </summary>
    public int TotalQuantitySold { get; private set; }

    /// <summary>
    /// Total revenue generated by this product.
    /// </summary>
    public decimal TotalRevenue { get; private set; }

    /// <summary>
    /// Currency code.
    /// </summary>
    public string Currency { get; private set; } = "USD";

    /// <summary>
    /// Number of orders containing this product.
    /// </summary>
    public int OrderCount { get; private set; }

    /// <summary>
    /// Number of unique customers who purchased this product.
    /// </summary>
    public int UniqueCustomers { get; private set; }

    /// <summary>
    /// First time this product was ordered.
    /// </summary>
    public DateTime? FirstOrderDateUtc { get; private set; }

    /// <summary>
    /// Most recent order date for this product.
    /// </summary>
    public DateTime? LastOrderDateUtc { get; private set; }

    /// <summary>
    /// Average quantity per order.
    /// </summary>
    public decimal AverageQuantityPerOrder { get; private set; }

    /// <summary>
    /// Average selling price (may differ from current price due to discounts/changes).
    /// </summary>
    public decimal AverageSellingPrice { get; private set; }

    /// <summary>
    /// When this aggregate was last calculated.
    /// </summary>
    public DateTime LastCalculatedUtc { get; private set; }

    private ProductSalesAggregate() { } // EF Core

    public static ProductSalesAggregate Create(
        Guid productId,
        string sku,
        string productName,
        string currency = "USD")
    {
        return new ProductSalesAggregate
        {
            Id = Guid.NewGuid(),
            ProductId = productId,
            Sku = sku,
            ProductName = productName,
            Currency = currency,
            TotalQuantitySold = 0,
            TotalRevenue = 0,
            OrderCount = 0,
            UniqueCustomers = 0,
            AverageQuantityPerOrder = 0,
            AverageSellingPrice = 0,
            LastCalculatedUtc = DateTime.UtcNow
        };
    }

    public void UpdateMetrics(
        int totalQuantitySold,
        decimal totalRevenue,
        int orderCount,
        int uniqueCustomers,
        DateTime? firstOrderDate,
        DateTime? lastOrderDate)
    {
        TotalQuantitySold = totalQuantitySold;
        TotalRevenue = totalRevenue;
        OrderCount = orderCount;
        UniqueCustomers = uniqueCustomers;
        FirstOrderDateUtc = firstOrderDate;
        LastOrderDateUtc = lastOrderDate;
        AverageQuantityPerOrder = orderCount > 0 ? (decimal)totalQuantitySold / orderCount : 0;
        AverageSellingPrice = totalQuantitySold > 0 ? totalRevenue / totalQuantitySold : 0;
        LastCalculatedUtc = DateTime.UtcNow;
    }
}
